spring.application.name=project_management

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# HIKARI CONNECTION POOL (Important for Supabase)
# ===============================

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000

# Disable prepared statement caching (CRITICAL FIX)
spring.datasource.hikari.data-source-properties.prepareThreshold=0

#JPA / Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8082

secretJwtString=judensiscute12345678910jKJLKJiscute12345678910kjkljkjlk
